### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by fut33v** [alexander-akhmetov/python-telegram#110]
for this import code from tutorial

`from telegram.client import Telegram`

 I got this exception:

`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fut33v/.local/lib/python3.6/site-packages/telegram/client.py", line 16, in <module>
    from telegram.utils import AsyncResult
ImportError: cannot import name 'AsyncResult'
`

what am I doing wrong?

**Comment by fut33v** [comment]
seems like that was a conflict with python-telegram-bot, everything is ok without it in virtualenv
