### ISSUE TITLE
Error on tg.login()

### ISSUE THREAD

**Issue by jagzmz** [alexander-akhmetov/python-telegram#2]
Traceback (most recent call last):
  File "pytele.py", line 7, in <module>
    database_encryption_key='mahesh',
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\client.py", line 81, in __init__
    library_path=library_path,
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\tdjson.py", line 37, in __init__
    self._build_client(library_path)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\tdjson.py", line 40, in _build_client
    self._tdjson = CDLL(library_path)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by jagzmz** [comment]
Same error on 32-bit python

**Comment by LeonardoRick** [comment]
Oh, that's important to know!
Any ideia about if it's going to bee available to windows in the future?

**Comment by alexander-akhmetov** [comment]
python-telegram has built-in tdlib for Linux and MacOS, but not for Windows. You can [build](https://tdlib.github.io/td/build.html?language=Python) tdlib yourself or use Docker or any pre-built version. When you have the file, you need to specify the full path to it to make it work with python-telegram:

```python
tg = Telegram(library_path ='/path', ...)
```
