### ISSUE TITLE
ValueError: invalid option string 'api_id': must start with a character '-'

### ISSUE THREAD

**Issue by aliasghar79** [alexander-akhmetov/python-telegram#216]
Hi
I have this problem when running the send_message.py

Traceback (most recent call last):
  File "command.py", line 17, in <module>
    parser.add_argument('api_id', '94575')
  File "/usr/lib64/python3.6/argparse.py", line 1324, in add_argument
    kwargs = self._get_optional_kwargs(*args, **kwargs)
  File "/usr/lib64/python3.6/argparse.py", line 1455, in _get_optional_kwargs
    raise ValueError(msg % args)
ValueError: invalid option string 'api_id': must start with a character '-'

**Comment by Smarandii** [comment]
you should execute script like this:
```shell
python3.9 send_message.py "here goes api id" "here goes api hash" "here goes phone"
```
do not edit source code (do not write your api_id and api_hash in file like you did in 17 line `parser.add_argument('api_id', '94575')`

**Comment by aliasghar79** [comment]
> you should execute script like this:
> 
> ```shell
> python3.9 send_message.py "here goes api id" "here goes api hash" "here goes phone"
> ```
> 
> do not edit source code (do not write your api_id and api_hash in file like you did in 17 line `parser.add_argument('api_id', '94575')`


Thank you
I received a new error😑

2021-09-18 22:13:24,989 [INFO] telegram.tdjson: Using shared library "/usr/local/lib/python3.6/site-packages/telegram/lib/linux/libtdjson.so"
Traceback (most recent call last):
  File "examples/send_message.py", line 19, in <module>
    database_encryption_key='changeme1234',
  File "/usr/local/lib/python3.6/site-packages/telegram/client.py", line 130, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/usr/local/lib/python3.6/site-packages/telegram/tdjson.py", line 27, in __init__
    self._build_client(library_path, verbosity)
  File "/usr/local/lib/python3.6/site-packages/telegram/tdjson.py", line 36, in _build_client
    self._tdjson = CDLL(library_path)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by Smarandii** [comment]
You need to install openssl package on your machine
