### ISSUE TITLE
error in 

### ISSUE THREAD

**Issue by Mohammadwh** [alexander-akhmetov/python-telegram#28]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/client.py", line 396, in _listen_to_td
    self._run_handlers(update)
  File "/usr/local/lib/python3.6/dist-packages/telegram/client.py", line 427, in _run_handlers
    self._workers_queue.put((handler,update),timeout=self._queue_put_timeout)
  File "/usr/lib/python3.6/queue.py", line 141, in put
    raise Full
queue.Full

hello guys 
how i can fix this and how i can work by many worker ?

**Comment by alexander-akhmetov** [comment]
Hi,

The `default_workers_queue_size` parameter specifies the queue size (1000 by default): 

```python
from telegram.client import Telegram

tg = Telegram(
    ...
    default_workers_queue_size=N,
    ...
)
```

Also, you can create your own worker and pass the class as a parameter to `Telegram`. There is only one [worker class](https://github.com/alexander-akhmetov/python-telegram/blob/master/telegram/worker.py#L23) in the library now.
