### ISSUE TITLE
how to fix this :(

### ISSUE THREAD

**Issue by Mohammadwh** [alexander-akhmetov/python-telegram#30]
Traceback (most recent call last):
  File "core.py", line 21, in <module>
    default_workers_queue_size = 1000,
  File "/usr/local/lib/python3.6/dist-packages/telegram/client.py", line 96, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/usr/local/lib/python3.6/dist-packages/telegram/tdjson.py", line 27, in __init__
    self._build_client(library_path, verbosity)
  File "/usr/local/lib/python3.6/dist-packages/telegram/tdjson.py", line 36, in _build_client
    self._tdjson = CDLL(library_path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/local/lib/python3.6/dist-packages/telegram/lib/linux/libtdjson.so)

hello guys how to fix this? :(

**Comment by alexander-akhmetov** [comment]
This is because of the incorrectly compiled `tdlib` library. Right now you can use the older `0.7.0` version or compile the `tdlib` yourself. I will try to release a fix soon.

**Comment by alexander-akhmetov** [comment]
I just uploaded a new version, `0.10.0`, please, try it.

**Comment by alexander-akhmetov** [comment]
Hi, do you still have this problem?

**Comment by Mohammadwh** [comment]
hello no i fix this thanks a lot of🌹
