### ISSUE TITLE
Error loading shared library libssl.so.1.0.0

### ISSUE THREAD

**Issue by jackdesert** [alexander-akhmetov/python-telegram#4]
First I start a shell inside the container:

    docker run -i -t --rm -v /tmp/docker-:/tmp/ akhmetov/python-telegram sh

From inside the container, I then cd to the examples directory

    cd /app/examples

and call get_me.py

    python3 get_me.py <id> <hash> <phone>

But this error occurs:

    Traceback (most recent call last):
      File "get_me.py", line 17, in <module>
        database_encryption_key='changeme1234',
      File "/usr/local/lib/python3.6/site-packages/telegram/client.py", line 81, in __init__     
        library_path=library_path,
      File "/usr/local/lib/python3.6/site-packages/telegram/tdjson.py", line 37, in __init__   
        self._build_client(library_path)
      File "/usr/local/lib/python3.6/site-packages/telegram/tdjson.py", line 40, in _build_client
        self._tdjson = CDLL(library_path)
      File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/local/lib/python3.6/site-packages/telegram/lib/linux/libtdjson.so)

**Comment by alexander-akhmetov** [comment]
Should be fixed with https://github.com/alexander-akhmetov/python-telegram/pull/20
